### ISSUE TITLE
`nvidia-smi` does not work

### ISSUE THREAD

**Issue by agude** [Lab41/nbserver#32]
`nvidia-smi` fails inside the container.

**Comment by agude** [comment]
This is a path problem. `/usr/local/cuda/bin` and `/usr/loca/nvidia/bin` are missing from the path.

**Comment by agude** [comment]
Closed by #34.

**Comment by agude** [comment]
#34 fixed this for `root`, it is still broken for non-root users. @ymt123: You have a theory as to why, yes?

**Comment by ymt123** [comment]
Maybe we need to add '/usr/local/nvidia/bin' to line 90 in https://github.com/Lab41/nbserver/blob/master/02_ganymede/ganymede/ganymede_nbserver.sh

**Comment by agude** [comment]
That looks right, I'll give it a shot.
